class MyErr isa Exception

def f(x: Int) raises [MyErr] => print "nothing"
def g(x: Int) => f(x)
